# This file was generated by the {rix} R package v0.17.2 on 2026-01-05
# with following call:
# >rix(date = "2026-01-05",
#  > r_pkgs = c("readxl",
#  > "dplyr",
#  > "tidyr",
#  > "purrr",
#  > "ggplot2",
#  > "scales",
#  > "patchwork",
#  > "vars",
#  > "forecast",
#  > "tseries",
#  > "urca",
#  > "lmtest",
#  > "ppcor",
#  > "glmnet",
#  > "lars",
#  > "knitr",
#  > "rmarkdown",
#  > "testthat",
#  > "reticulate"),
#  > system_pkgs = c("git",
#  > "quarto"),
#  > py_conf = list(py_version = "3.11",
#  > py_pkgs = c("pandas",
#  > "numpy",
#  > "matplotlib",
#  > "statsmodels",
#  > "scikit-learn",
#  > "openpyxl",
#  > "pytest")),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > r_ver = "4.5.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-01-05.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      dplyr
      forecast
      ggplot2
      glmnet
      knitr
      lars
      lmtest
      patchwork
      ppcor
      purrr
      readxl
      reticulate
      rmarkdown
      scales
      testthat
      tidyr
      tseries
      urca
      vars;
  };
   
  pyconf = builtins.attrValues {
    inherit (pkgs.python311Packages) 
      pip
      ipykernel
      matplotlib
      numpy
      openpyxl
      pandas
      pytest
      scikit-learn
      statsmodels;
  };
   
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      git
      glibcLocales
      nix
      python311
      quarto
      R
      pandoc
      which;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    RETICULATE_PYTHON = "${pkgs.python311}/bin/python";

    buildInputs = [ rpkgs pyconf system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
